[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/d/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/wohnung/*"
  to = "/index.html"
  status = 200
